package wfrpovtestcases;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.SpinnerNumberModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowProgress.java
 *
 * Created on 28-nov-2012, 11:43:44
 */
/**
 *
 * @author DGarijo
 */
public class ShowProgress extends javax.swing.JFrame {
    private CheckTestCases ck;

    /** Creates new form ShowProgress */
    public ShowProgress() {
        initComponents();
        this.labelLoading.setVisible(false);
        this.spinnerSelectNumber.setModel(new SpinnerNumberModel(1, 1, 17, 1));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
 
        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        this.setLocation(x, y);
        
        //initiate the test cases:
        ck = new CheckTestCases();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTestAllTestCases = new javax.swing.JButton();
        pannelLog = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        labelLog = new javax.swing.JLabel();
        labelTestCaseNo = new javax.swing.JLabel();
        spinnerSelectNumber = new javax.swing.JSpinner();
        buttonTestOneTestCase = new javax.swing.JButton();
        labelLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Cases ");
        setResizable(false);

        buttonTestAllTestCases.setText("test all test cases!");
        buttonTestAllTestCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTestAllTestCasesActionPerformed(evt);
            }
        });

        logTextArea.setColumns(20);
        logTextArea.setEditable(false);
        logTextArea.setRows(5);
        pannelLog.setViewportView(logTextArea);

        labelLog.setText("LOG:");

        labelTestCaseNo.setText("Test testcase nº");

        buttonTestOneTestCase.setText("test");
        buttonTestOneTestCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTestOneTestCaseActionPerformed(evt);
            }
        });

        labelLoading.setText("Loading ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLog)
                .addContainerGap(415, Short.MAX_VALUE))
            .addComponent(pannelLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonTestAllTestCases, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelTestCaseNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerSelectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTestOneTestCase)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLoading)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTestAllTestCases)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTestCaseNo)
                            .addComponent(spinnerSelectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTestOneTestCase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLog))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelLoading)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelLog, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTestOneTestCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTestOneTestCaseActionPerformed
        String tcResult = "";       
        int selection = Integer.parseInt(""+this.spinnerSelectNumber.getValue());
//        System.out.println(selection);        
        switch (selection){
            case 1: tcResult = ck.checkTestCase1();break;
            case 2: tcResult = ck.checkTestCase2();break;
            case 3: tcResult = ck.checkTestCase3();break;
            case 4: tcResult = ck.checkTestCase4();break;
            case 5: tcResult = ck.checkTestCase5();break;
            case 6: tcResult = ck.checkTestCase6();break;
            case 7: tcResult = ck.checkTestCase7();break;
            case 8: tcResult = ck.checkTestCase8();break;
            case 9: tcResult = ck.checkTestCase9();break;
            case 10: tcResult = ck.checkTestCase10();break;
            case 11: tcResult = ck.checkTestCase11();break;
            case 12: tcResult = ck.checkTestCase12();break;
            case 13: tcResult = ck.checkTestCase13();break;
            case 14: tcResult = ck.checkTestCase14();break;
            case 15: tcResult = ck.checkTestCase15();break;
            case 16: tcResult = ck.checkTestCase16();break;
            case 17: tcResult = ck.checkTestCase17();break;
        }
        this.logTextArea.append("Test Case "+selection+": "+ tcResult + "\n");
        //regular log exit
        System.out.println(tcResult);
       
    }//GEN-LAST:event_buttonTestOneTestCaseActionPerformed

    private void buttonTestAllTestCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTestAllTestCasesActionPerformed
        for (int i = 0; i<17;i++){
            ThreadForQueries tfq = new ThreadForQueries(ck, logTextArea, i+1);
            tfq.start();            
        }
    }//GEN-LAST:event_buttonTestAllTestCasesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ShowProgress().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTestAllTestCases;
    private javax.swing.JButton buttonTestOneTestCase;
    private javax.swing.JLabel labelLoading;
    private javax.swing.JLabel labelLog;
    private javax.swing.JLabel labelTestCaseNo;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JScrollPane pannelLog;
    private javax.swing.JSpinner spinnerSelectNumber;
    // End of variables declaration//GEN-END:variables
}
